"""Add attribution_source to ScanLog

Revision ID: 48cd95911510
Revises: 2bcef7fb5160
Create Date: 2026-09-29 15:53:46.217524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cd95911510'
down_revision = '2bcef7fb5160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribution_source', sa.String(length=20), server_default='camera', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.drop_column('attribution_source')

    # ### end Alembic commands ###
